FROM golang:1.12-stretch
RUN apt-get update -y
RUN apt-get install -y rsyslog

COPY ./docker.d/api/rsyslog.conf /etc/rsyslog.conf
COPY ./docker-entrypoint.api.sh /entrypoint.sh

ARG code_dir

ENV ENV development
ENV CODE_DIR $code_dir
COPY . $code_dir
WORKDIR $code_dir
RUN go build -o story-book-api
ENTRYPOINT ["/entrypoint.sh"]